services:
  db:
    image: postgres:15
    container_name: kanban_postgres
    restart: always
    environment:
      POSTGRES_USER: kanban_db
      POSTGRES_PASSWORD: cV@Q6-7zBdf6NKpU-4ojv7EdUCbDWQ7g
      POSTGRES_DB: kanban_board_prod
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
